# Generated by Django 2.0.2 on 2018-08-31 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 31, 9, 38, 25, 286861)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 31, 9, 38, 37, 727781)),
            preserve_default=False,
        ),
    ]
