# Generated by Django 2.0.2 on 2018-09-03 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('take_test', 'Can take tests'), ('create_test', 'Can create tests'))},
        ),
    ]
