# Generated by Django 2.0.2 on 2018-08-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180831_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attemptsallowed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='wordlimit',
            field=models.IntegerField(default=150),
        ),
    ]
