# Generated by Django 2.0.7 on 2018-08-31 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180831_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
