# Generated by Django 2.0.2 on 2018-08-31 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_question_date'),
        ('myapp', '0003_auto_20180831_1931'),
    ]

    operations = [
    ]
