# Generated by Django 2.0.2 on 2018-08-31 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_merge_20180831_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date',
            new_name='datecreated',
        ),
        migrations.RemoveField(
            model_name='question',
            name='no_of_attempts',
        ),
        migrations.RemoveField(
            model_name='question',
            name='word_limit',
        ),
    ]
