# Generated by Django 2.0.2 on 2018-09-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180831_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='attemptsallowed',
            new_name='attempts_allowed',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='datecreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='wordlimit',
            new_name='word_limit',
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=30),
        ),
    ]
