# Generated by Django 2.0.2 on 2018-09-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180901_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='word_limit',
            field=models.IntegerField(default=300),
        ),
    ]
